In [1]:
# Importación de librerías necesarias
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
# Datos de los productos basados en las categorías
def load_data():
    data = {
        'Product': ['Tejido Orgánico', 'Tejido Reciclado', 'Lino', 'Algodón', 'Rayas Marineras', 
                    'Cuadros Escoceses', 'Tie-Dye', 'Tejido Jacquard Floral', 'Tejido Técnico Reflectante'],
        'Category': ['Sostenible', 'Sostenible', 'Básicos y Naturales', 'Básicos y Naturales', 
                     'Rayas y Cuadros', 'Rayas y Cuadros', 'Lavados y Engrasados', 'Jacquard', 'Técnicos'],
        'Price': [25.99, 23.99, 19.99, 15.99, 18.99, 21.99, 16.99, 30.99, 35.99]
    }
    products = pd.DataFrame(data)
    
    # Guardar los datos en un archivo CSV
    products.to_csv('products_data.csv', index=False)
    print("Products data has been saved to 'products_data.csv'")
    
    return products

In [3]:
# Leer los datos
products = load_data()

Products data has been saved to 'products_data.csv'


In [4]:
# Mostrar los primeros registros del dataframe
print(products.head())

            Product             Category  Price
0   Tejido Orgánico           Sostenible  25.99
1  Tejido Reciclado           Sostenible  23.99
2              Lino  Básicos y Naturales  19.99
3           Algodón  Básicos y Naturales  15.99
4   Rayas Marineras      Rayas y Cuadros  18.99


In [8]:
products

Product              Category  Price
0             Tejido Orgánico            Sostenible  25.99
1            Tejido Reciclado            Sostenible  23.99
2                        Lino   Básicos y Naturales  19.99
3                     Algodón   Básicos y Naturales  15.99
4             Rayas Marineras       Rayas y Cuadros  18.99
5           Cuadros Escoceses       Rayas y Cuadros  21.99
6                     Tie-Dye  Lavados y Engrasados  16.99
7      Tejido Jacquard Floral              Jacquard  30.99
8  Tejido Técnico Reflectante              Técnicos  35.99

In [7]:
# Convertir las categorías en variables dummy (una columna por cada categoría)
products_encoded = pd.get_dummies(products, columns=['Category'])
products_encoded

Product  Price  Category_Básicos y Naturales  \
0             Tejido Orgánico  25.99                         False   
1            Tejido Reciclado  23.99                         False   
2                        Lino  19.99                          True   
3                     Algodón  15.99                          True   
4             Rayas Marineras  18.99                         False   
5           Cuadros Escoceses  21.99                         False   
6                     Tie-Dye  16.99                         False   
7      Tejido Jacquard Floral  30.99                         False   
8  Tejido Técnico Reflectante  35.99                         False   

   Category_Jacquard  Category_Lavados y Engrasados  Category_Rayas y Cuadros  \
0              False                          False                     False   
1              False                          False                     False   
2              False                          False                     False   
3              False                          False                     False   
4              False                          False                      True   
5              False                          False                      True   
6              False                           True                     False   
7               True                          False                     False   
8              False                          False                     False   

   Category_Sostenible  Category_Técnicos  
0                 True              False  
1                 True              False  
2                False              False  
3                False              False  
4                False              False  
5                False              False  
6                False              False  
7                False              False  
8                False               True

In [9]:
# Extraer solo las columnas numéricas (sin el nombre del producto)
products_numeric = products_encoded.drop('Product', axis=1)
products_numeric

Price  Category_Básicos y Naturales  Category_Jacquard  \
0  25.99                         False              False   
1  23.99                         False              False   
2  19.99                          True              False   
3  15.99                          True              False   
4  18.99                         False              False   
5  21.99                         False              False   
6  16.99                         False              False   
7  30.99                         False               True   
8  35.99                         False              False   

   Category_Lavados y Engrasados  Category_Rayas y Cuadros  \
0                          False                     False   
1                          False                     False   
2                          False                     False   
3                          False                     False   
4                          False                      True   
5                          False                      True   
6                           True                     False   
7                          False                     False   
8                          False                     False   

   Category_Sostenible  Category_Técnicos  
0                 True              False  
1                 True              False  
2                False              False  
3                False              False  
4                False              False  
5                False              False  
6                False              False  
7                False              False  
8                False               True

In [26]:
products['Product']

0               Tejido Orgánico
1              Tejido Reciclado
2                          Lino
3                       Algodón
4               Rayas Marineras
5             Cuadros Escoceses
6                       Tie-Dye
7        Tejido Jacquard Floral
8    Tejido Técnico Reflectante
Name: Product, dtype: object

In [27]:
#MANUALMENTE:
product_name = products['Product'][3]
product_name

'Algodón'

In [28]:
# Obtener el índice del producto seleccionado
product_idx = products[products['Product'] == product_name].index[0]
product_idx

3

In [29]:
# Calcular la similitud usando cosine similarity
similarity_matrix = cosine_similarity(products_numeric)
similarity_matrix

array([[1.        , 0.99999487, 0.99801262, 0.9973122 , 0.99787801,
        0.99822897, 0.99753423, 0.99874077, 0.9988751 ],
       [0.99999487, 1.        , 0.99788453, 0.99718419, 0.99774993,
        0.99810085, 0.9974062 , 0.99861258, 0.99874689],
       [0.99801262, 0.99788453, 1.        , 0.9999222 , 0.9973692 ,
        0.99771999, 0.9970256 , 0.99823152, 0.99836578],
       [0.9973122 , 0.99718419, 0.9999222 , 1.        , 0.99666922,
        0.99701977, 0.99632586, 0.99753094, 0.99766511],
       [0.99787801, 0.99774993, 0.9973692 , 0.99666922, 1.        ,
        0.99997432, 0.99689111, 0.99809688, 0.99823112],
       [0.99822897, 0.99810085, 0.99771999, 0.99701977, 0.99997432,
        1.        , 0.99724173, 0.99844792, 0.99858221],
       [0.99753423, 0.9974062 , 0.9970256 , 0.99632586, 0.99689111,
        0.99724173, 1.        , 0.99775302, 0.99788722],
       [0.99874077, 0.99861258, 0.99823152, 0.99753094, 0.99809688,
        0.99844792, 0.99775302, 1.        , 0.99909419],


In [30]:
# Obtener las recomendaciones (similitudes más altas)
recommendations = similarity_matrix[product_idx]
recommendations

array([0.9973122 , 0.99718419, 0.9999222 , 1.        , 0.99666922,
       0.99701977, 0.99632586, 0.99753094, 0.99766511])

In [31]:
# Ordenar las recomendaciones por similitud (de mayor a menor)
recommended_indices = recommendations.argsort()[-4:-1][::-1]  # Top 3 recomendaciones
recommended_indices

array([2, 8, 7])

In [32]:
# Obtener los productos recomendados
recommended_products = products['Product'].iloc[recommended_indices]
recommended_products

2                          Lino
8    Tejido Técnico Reflectante
7        Tejido Jacquard Floral
Name: Product, dtype: object

In [23]:
# Función para generar recomendaciones basadas en similitudes
def recommend_product(product_name, products):
    # Convertir las categorías en variables dummy (una columna por cada categoría)
    products_encoded = pd.get_dummies(products, columns=['Category'])
    
    # Extraer solo las columnas numéricas (sin el nombre del producto)
    products_numeric = products_encoded.drop('Product', axis=1)
    
    # Obtener el índice del producto seleccionado
    product_idx = products[products['Product'] == product_name].index[0]
    
    # Calcular la similitud usando cosine similarity
    similarity_matrix = cosine_similarity(products_numeric)
    
    # Obtener las recomendaciones (similitudes más altas)
    recommendations = similarity_matrix[product_idx]
    
    # Ordenar las recomendaciones por similitud (de mayor a menor)
    recommended_indices = recommendations.argsort()[-4:-1][::-1]  # Top 3 recomendaciones
    
    # Obtener los productos recomendados
    recommended_products = products['Product'].iloc[recommended_indices]
    
    return recommended_products

In [24]:
# Selección de un producto para la recomendación
selected_product = 'Algodón'

In [25]:
# Mostrar las recomendaciones para el producto seleccionado
recommended_products = recommend_product(selected_product, products)
print(f"Selected Product: {selected_product}")
print("Recommended products:")
print(recommended_products)

Selected Product: Algodón
Recommended products:
2                          Lino
8    Tejido Técnico Reflectante
7        Tejido Jacquard Floral
Name: Product, dtype: object
